// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBf6y2FDOFtFsRxaGaNm1AR5t4vsB6ms2I',
    appId: '1:499219248127:web:22d6dbe2c231b692eb2dca',
    messagingSenderId: '499219248127',
    projectId: 'fastkro-5e2a5',
    authDomain: 'fastkro-5e2a5.firebaseapp.com',
    storageBucket: 'fastkro-5e2a5.firebasestorage.app',
    measurementId: 'G-JMT1GCC911',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDTtCu0EeGIC1p3nJOyPgS6UlS3RMaWe_0',
    appId: '1:499219248127:android:c3ba007c4affb2f5eb2dca',
    messagingSenderId: '499219248127',
    projectId: 'fastkro-5e2a5',
    storageBucket: 'fastkro-5e2a5.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDNERj4M5kYrMAE_K3lhk8N2BHF4o0_FFA',
    appId: '1:499219248127:ios:15d088ac8fe6f584eb2dca',
    messagingSenderId: '499219248127',
    projectId: 'fastkro-5e2a5',
    storageBucket: 'fastkro-5e2a5.firebasestorage.app',
    iosBundleId: 'com.example.mobile',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDNERj4M5kYrMAE_K3lhk8N2BHF4o0_FFA',
    appId: '1:499219248127:ios:15d088ac8fe6f584eb2dca',
    messagingSenderId: '499219248127',
    projectId: 'fastkro-5e2a5',
    storageBucket: 'fastkro-5e2a5.firebasestorage.app',
    iosBundleId: 'com.example.mobile',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBf6y2FDOFtFsRxaGaNm1AR5t4vsB6ms2I',
    appId: '1:499219248127:web:b20dc174a8f364a3eb2dca',
    messagingSenderId: '499219248127',
    projectId: 'fastkro-5e2a5',
    authDomain: 'fastkro-5e2a5.firebaseapp.com',
    storageBucket: 'fastkro-5e2a5.firebasestorage.app',
    measurementId: 'G-P13NYYGW0F',
  );
}
